- name: Установка зависимостей
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: no

- name: Проверка существования GPG-ключа ClickHouse
  stat:
    path: /usr/share/keyrings/clickhouse-keyring.gpg
  register: key_stat

- name: Добавление GPG-ключа ClickHouse
  become: yes
  shell: |
    curl -fsSL 'https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key' | gpg --dearmor -o /usr/share/keyrings/clickhouse-keyring.gpg
  args:
    executable: /bin/bash
  when: not key_stat.stat.exists

- name: Добавление APT-репозитория ClickHouse
  become: yes
  copy:
    content: "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb stable main"
    dest: /etc/apt/sources.list.d/clickhouse.list
    mode: '0644'

- name: Обновление кэша пакетов
  become: yes
  apt:
    update_cache: yes

- name: Установка пакетов ClickHouse
  become: yes
  apt:
    name:
      - clickhouse-server
      - clickhouse-client
      - clickhouse-common-static
      - clickhouse-odbc-bridge
      - clickhouse-library-bridge
    state: present

- name: Создание директорий для Keeper
  file:
    path: "{{ item }}"
    state: directory
    owner: clickhouse
    group: clickhouse
  loop:
    - /var/lib/clickhouse/coordination/log
    - /var/lib/clickhouse/coordination/snapshots

- name: Настройка ClickHouse Keeper
  copy:
    content: |
      <clickhouse>
        <keeper_server>
          <tcp_port>9181</tcp_port>
          <server_id>{% if inventory_hostname == 'srv-ch-01' %}1{% else %}2{% endif %}</server_id>
          <listen_host>0.0.0.0</listen_host>
          <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
          <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
          <session_timeout_ms>30000</session_timeout_ms>
          <operation_timeout_ms>10000</operation_timeout_ms>
          <raft_configuration>
            <server>
              <id>1</id>
              <hostname>10.1.15.51</hostname>
              <port>9444</port>
            </server>
            <server>
              <id>2</id>
              <hostname>10.1.15.53</hostname>
              <port>9444</port>
            </server>
          </raft_configuration>
        </keeper_server>

        <zookeeper>
          <node>
            <host>10.1.15.51</host>
            <port>9181</port>
            <priority>1</priority>
          </node>
          <node>
            <host>10.1.15.53</host>
            <port>9181</port>
            <priority>2</priority>
          </node>
        </zookeeper>
      </clickhouse>
    dest: /etc/clickhouse-server/config.d/keeper.xml
    owner: clickhouse
    group: clickhouse
    mode: '0644'

- name: Настройка macros.xml
  copy:
    content: |
      <clickhouse>
        <macros>
          {% if inventory_hostname == 'srv-ch-01' %}
          <replica>srv-ch-01</replica>
          {% else %}
          <replica>srv-ch-02</replica>
          {% endif %}
          <cluster>clickhouse_cluster</cluster>
          <shard>shard01</shard>
        </macros>      </clickhouse>
    dest: /etc/clickhouse-server/config.d/macros.xml
    owner: clickhouse
    group: clickhouse

- name: Конфигурация кластера
  copy:
    content: |
      <clickhouse>
          {% if inventory_hostname == 'srv-ch-01' %}
       <interserver_http_host>10.1.15.51</interserver_http_host>
          {% else %}
       <interserver_http_host>10.1.15.53</interserver_http_host>
          {% endif %}
       <interserver_http_credentials>
        <user>interserver</user>
        <password>interserver_password</password>
       </interserver_http_credentials>

        <remote_servers>
          <clickhouse_cluster>
            <shard>
              <internal_replication>true</internal_replication>
              <replica><host>10.1.15.51</host><port>9000</port></replica>
              <replica><host>10.1.15.53</host><port>9000</port></replica>
            </shard>
          </clickhouse_cluster>
        </remote_servers>
      </clickhouse>
    dest: /etc/clickhouse-server/config.d/clusters.xml

- name: Настройка start.xml
  copy:
    content: |
     <clickhouse>
      <listen_host>0.0.0.0</listen_host>
        <logger>
          <level>information</level>
          <log>/var/log/clickhouse-server/clickhouse-server.log</log>
          <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
          <size>1000M</size>
          <count>10</count>
        </logger>
     </clickhouse>
    dest: /etc/clickhouse-server/config.d/start.xml
    owner: clickhouse
    group: clickhouse

- name: Перезапуск ClickHouse
  systemd:
    name: clickhouse-server
    state: restarted
    enabled: yes
