- name: Установка PostgreSQL 14
  become: yes
  apt:
    name: postgresql
    state: present
    update_cache: yes

- name: Включение wal_level = logical в postgresql.conf
  become: yes
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: '^#?wal_level\s*='
    line: 'wal_level = logical'
    backup: yes

- name: Разрешить подключения с любого хоста (listen_addresses)
  become: yes
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '0.0.0.0'"
    backup: yes

- name: Добавить правило для логической репликации в pg_hba.conf
  become: yes
  lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    line: "host replication all all md5"
    regexp: "^host\\s+replication\\s+all\\s+all\\s+md5$"
    backup: yes

- name: Разрешить подключения ко всем БД с любого IP
  become: yes
  lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    line: "host all all all md5"
    regexp: "^host\\s+all\\s+all\\s+all\\s+md5$"
    backup: yes

- name: Перезапуск PostgreSQL
  become: yes
  systemd:
    name: postgresql
    state: restarted

- name: Копирование init.sql
  copy:
    src: ../../../config/postgres-init.sql
    dest: /tmp/init.sql

- name: Запуск init.sql
  become: yes
  become_user: postgres
  command: psql -f /tmp/init.sql

