- name: Установка PostgreSQL
  apt:
    name: postgresql, postgresql-contrib
    state: present

- name: Включение логической репликации
  lineinfile:
    path: /etc/postgresql/*/main/postgresql.conf
    regexp: '^wal_level'
    line: 'wal_level = logical'
  notify: restart postgresql

- name: Копирование init.sql
  copy:
    src: ../../../config/postgres-init.sql
    dest: /tmp/init.sql

- name: Запуск init.sql
  become: yes
  become_user: postgres
  command: psql -f /tmp/init.sql

- name: Установка Java
  apt:
    name: openjdk-11-jre-headless
    state: present

- name: Скачать и распаковать Kafka
  unarchive:
    src: https://downloads.apache.org/kafka/3.7.0/kafka_2.13-3.7.0.tgz
    dest: /opt
    remote_src: yes

- name: Симлинк kafka
  file:
    src: /opt/kafka_2.13-3.7.0
    dest: /opt/kafka
    state: link

- name: Генерация Node ID
  command: /opt/kafka/bin/kafka-storage.sh random-uuid
  register: node_id
  changed_when: false

- name: Сохранение Node ID
  copy:
    content: "{{ node_id.stdout }}"
    dest: /opt/kafka/node_id

- name: Настройка server.properties
  copy:
    content: |
      process.roles=broker,controller
      node.id={{ lookup('file', '/opt/kafka/node_id') }}
      controller.quorum.voters=1@srv-db-01:9093
      listeners=PLAINTEXT://0.0.0.0:9092
      advertised.listeners=PLAINTEXT://srv-db-01:9092
      log.dirs=/tmp/kafka-logs
    dest: /opt/kafka/config/kraft/server.properties

- name: Форматирование хранилища
  command: /opt/kafka/bin/kafka-storage.sh format -t "{{ lookup('file', '/opt/kafka/node_id') }}" -c /opt/kafka/config/kraft/server.properties
  args:
    creates: /tmp/kafka-logs/meta.properties

- name: Создание сервиса Kafka
  copy:
    dest: /etc/systemd/system/kafka.service
    content: |
      [Unit]
      Description=Kafka
      After=network.target
      [Service]
      ExecStart=/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties
      ExecStop=/opt/kafka/bin/kafka-server-stop.sh
      [Install]
      WantedBy=multi-user.target

- name: Запуск Kafka
  systemd:
    name: kafka
    state: started
    enabled: yes
