- name: Установка зависимостей
  become: yes
  apt:
    name: [curl, wget, ca-certificates, docker.io]
    state: present
    update_cache: yes

- name: Проверка, установлен ли abctl
  command: which abctl
  register: abctl_check
  ignore_errors: yes
  changed_when: false

- name: Установка Airbyte CLI (abctl) через официальный скрипт
  become: yes
  shell: |
    DIR_INSTALL=/usr/local/bin \
    curl -LsfS https://get.airbyte.com | bash -
  environment:
    DIR_INSTALL: /usr/local/bin
    DIR_TMP: /tmp/abctl_install
  when: abctl_check.rc != 0

- name: Установка Airbyte в Docker
  become: yes
  command: abctl local install --insecure-cookies
  environment:
    DIR_INSTALL: /opt/airbyte
  creates: /opt/airbyte/docker-compose.yaml
